### ISSUE TITLE
How to access figma.getLocaleXStyles()

### ISSUE THREAD

**Issue by tooppaaa** [react-figma/react-figma#345]
Hello,

Thanks for this library.

I'm currently investigating how to use and build Locale Styles
![image](https://user-images.githubusercontent.com/599163/91101780-1b771e00-e668-11ea-9fab-ed873292aa1f.png)

I manage to access the [figma API](https://www.figma.com/plugin-docs/api/figma/#createpaintstyle) from code.ts and create all my styles.

I am now hoping to reuse them from my component without success. Am I missing something in the docs ?

```ts
const Palettes: React.FC<PalettesProps> = ({ ...props }) => {
  const theme = useTheme();
  const styles = figma.getLocalPaintStyles(); // throw figma is not defined at runtime
  return ...
}
```

If it's not available yet, happy to help through a PR with your guidance ;)

**Comment by ilyalesik** [comment]
Local Styles is not supported right now. If you can make PR, it's welcomed. 🙌

There is a related issue: https://github.com/react-figma/react-figma/issues/344

I think that `react-sketchapp` way is most useful: just creating `StyleSheet` analog for local styles, e.g.:

```
const styles = TextStyles.create({
   h1: {
     fontSize: "..."
   }
});

const Component = () => {
  return <Text style={styles.h1} />
}
```

But not sure how it will with hydration (plugin relaunching).

**Comment by naoufal** [comment]
@tooppaaa @ilyalesik I started looking into added Shared Styles support, namely `TextStyles`, `PaintStyles` & `EffectStyles`.  While the `react-sketchapp` API works for `TextStyles` it kinda breaks down with `PaintStyles`.  Mostly because `PaintStyles` are defined as colors that can be used for a stroke, fill and/or text color.

So in the context of a `View`, applying PaintStyles using the `style` prop doesn't clearly dictate which style property it should be applied to.

```jsx
const paintStyles = PaintStyles.create({
  red: {
    color: 'red'
  }
});

// Is this paintStyle be applied as a borderColor or backgroundColor
<View style={paintStyles.red} />
```

I wonder if added a `sharedStyle` prop wouldn't give us a little more power. Something like:
```jsx
const paintStyles = PaintStyles.create({
  red: {
    color: 'red'
  }
});

// Is this paintStyle be applied as a borderColor or backgroundColor
<View 
  sharedStyles={{
    fillStyle: paintStyles.red,
    backgroundColorStyle: paintStyles.red// alias for fillStyle
    strokeStyle: paintStyles.red,
    borderColorStyle: paintStyles.red // alias for strokeStyle
  }}
  style={styles.someCustomStyles}
>
  <Text 
    sharedStyles={{ 
      textStyle: paintStyles.red 
      color: paintStyles.red // alias for textStyle
    }}
  >
    Some Text
  </Text>
</View>
```

The keys would map to Figma's `textStyleId` `fillStyleId`, `strokeStyleId`, `effectStyleId` and `gridStyleId`.

As for creating TextStyles/PaintStyles/EffectStyles,  their .create() method would return the object but append a `_id` key that would be map the `localStyleIds` created by Figma.

API for the create methods would look something like:

```es6
function create(sharedStyles = {}, options = { clearExistingStyles: false, updateExistingStyles: false }) {}
```

It's worth noting that the PaintStyle.create API is working with the constraint that SharedStyles as formatted like StyleSheet styles.  

Alternatively, PaintStyles could be defined as a single value (forcing users to use `rgba` when transparency is required).  But this would also propose different APIs for PaintStyles/TextStyles/EffectStyles.

Would love to get your thoughts on this.

**Comment by ilyalesik** [comment]
@naoufal API that you suggested looks awesome!

So, `sharedStyles` is for accessing to `TextStyles` etc.?

**Comment by ilyalesik** [comment]
The [Local Styles](https://react-figma.dev/docs/local-styles) API.
