### ISSUE TITLE
Screenshot Test in Figma?

### ISSUE THREAD

**Issue by cyan33** [react-figma/react-figma#390]
Hey team! We've been building our customized variants of figma components and wanted to bring in and add screenshots tests to the variants.

Currently we use puppeteer + jest-image-snap to render the component in web, and then take screenshot on top of that. But since react-figma renders things differently than web, we wanted to have an in-house solution that makes sure our components don't break in figma canvas when we're adding changes. 

Any thoughts or experience in doing that?

**Comment by ilyalesik** [comment]
Hey, @cyan33!

Not sure that it's possible to make a 'real' snapshot from Figma because Figma hasn't CI/CD features. As an alternative, I can offer to use [figma-api-stub](https://github.com/react-figma/figma-api-stub) - a stub implementation Figma Plugins API. It generates a plain javascript nodes tree (similar to Figma nodes), and it's possible to take a usual snapshot by jest. An example:

```tsx
import * as React from 'react';
import { createFigma } from 'figma-api-stub';
import { render, View, Page } from 'react-figma';
import { wait } from 'helpers/wait';

describe('test', () => {
    beforeEach(() => {
        // @ts-ignore
        global.figma = createFigma({
            simulateErrors: true
        });
    });

    it('it', async () => {
       await render(<Page>
           <View />
        </Page>);
       await wait();
       expect(removeMeta(figma.root)).toMatchSnapshot();
    });
});
```

I use this approach for testing react-figma codebase.

**Comment by cyan33** [comment]
@ilyalesik Thanks for the input! I think this works perfectly for our case. It doesn't need to be a screenshot per se. As long as it's a source of truth that is based off from `react-figma`'s renderer, I think it's sufficient. Appreciate it!
