### ISSUE TITLE
Aligning with React Native API - proposal

### ISSUE THREAD

**Issue by macintoshhelper** [react-figma/react-figma#49]
Hi, just discovered this repo and am excited to see this be developed!

I was wondering whether it would be possible to tend towards using a React Native style API for the project? e.g. `<View>` as a generic core component API instead of `<Rectangle>` or `<Circle>`, etc. I've found with `react-sketchapp` that the `Svg` API acts as a really nice escape hatch for using shape-specific components if you need a `<Circle>` instead of `<View style={{ borderRadius: '50%' }}>` for some reason.

e.g.

`src/svg.js`
```js
const Svg = {
  rect: RectangleRenderer,
  path: PathRenderer,
};
```

`src/index.js`
```js
export { View, Text, Image };

export { Svg };
```

Also, regarding components like #20 , I feel that these should live in another library, and that `react-figma` can provide "internal hooks" to Figma specific components intended for library use.

e.g.

npm: `react-primitives-shapes`

```js
const { View } from 'react-primitives';
const { Svg, Path } = require('react-primitives-svg');
const { shapes } = require('react-figma');

const Rectangle = (props) => <View style={{ display: 'flex' }} {...props} />;

const Star = Platform.OS === 'figma'
  ? shapes.Star 
  : (
    <Svg>
     <Path data="starhere..." />
    </Svg>
  );

module.exports = { Rectangle, Star };
```

This would help a lot with `react-primitives` support and with standardising React cross-platform usage to center around a core, shared API, with platform-specific as opt-in components. For me, a lot of the value of this project would be in using existing React Native or React Sketch.app codebases to render design systems/UI libraries to Figma.

**Comment by ilyalesik** [comment]
Hi, @macintoshhelper! Thank you for very interesting ideas. I think compatibility with existing React Sketch.app codebase is important. I had not thought about this before.

At the start of the project I tried to maximize compatibility with Figmа API e.g. 
`<Rectangle x={10} y={20} />` equal to
```
const rect = figma.createRectangle();
rect.x = 10;
rect.y = 10;
```
because did not know how users will use react-figma, and they are unlikely to want to learn different API ([feedback confirm this](https://github.com/simareeno/figma-and-production/issues/2)). 

Then I got that CSS-like `style` tag support is more convenient than using Figma API-like props for many cases, especially for building design systems. As a reference, I used [react-sketchapp styling](http://airbnb.io/react-sketchapp/docs/styling.html).

I am afraid that Figma nesting limitations may hinder the implementation of universal rendering ideas. E.g. we can't put rectangle to rectangle or put frame to frame. What are you think about this?

**Comment by macintoshhelper** [comment]
Could you provide more details on the nesting limitations? I ran into limitations with Adobe XD with grouping items being very unreliable, I couldn't find a way to do groups nested under groups.

Is it not possible to create `View` layers with nested children? Have a group with a visible or invisible rectangle as the background/frame for the group, and optional children.

**Comment by ilyalesik** [comment]
The inconvenience of Figma grouping API is the main limitation now. Issue #6 have more details.

**Comment by corysimmons** [comment]
Thoughts on just aligning with react-native-web's API and then we can just copy/paste components from our design systems to any target device?

**Comment by ilyalesik** [comment]
Hi, @corysimmons!

The main components of react-native(-web) are supported right now:

* [View](https://react-figma.now.sh/src/components/view/View.html)
* [Text](https://react-figma.now.sh/src/components/text/Text.html)
* [StyleSheet](https://react-figma.now.sh/src/helpers/StyleSheet.html)
* [Platform](https://react-figma.now.sh/src/helpers/Platform.html)
* [Image](https://react-figma.now.sh/src/components/Image/Image.html)

Also, you can use Webpack aliasing for universal rendering into multiple platforms:

```javascript
    resolve: {
        alias: {
            'react-native$': 'react-figma'
        }
    }
```

**Comment by corysimmons** [comment]
@ilyalesik Awesome! Thanks for all your hard work on this project! It looks like it has the potential to revolutionize designer<->dev workflows.
